#!/usr/bin/env bun

import { z } from "zod";
import { zodToJsonSchema } from "zod-to-json-schema";
import { writeFileSync } from "node:fs";
import { join } from "node:path";

import { createSessionExtension } from "../extensions/session/src/index";
import { createVoiceExtension } from "../extensions/voice/src/index";
import { createIMessageExtension } from "../extensions/imessage/src/index";
import { createChatExtension } from "../extensions/chat/src/index";
import { createControlExtension } from "../extensions/control/src/index";
import { createMemoryExtension } from "../extensions/memory/src/index";
import { createHooksExtension } from "../extensions/hooks/src/index";
import createDominatrixExtension from "../extensions/dominatrix/src/index";
import { createCodexExtension } from "../extensions/codex/src/index";

type MethodDef = {
  method: string;
  description: string;
  inputSchema: z.ZodTypeAny;
  source: "gateway" | "extension";
};

// Only the 4 real gateway-native methods — everything else lives in extensions
const gatewayMethods: MethodDef[] = [
  {
    method: "gateway.list_methods",
    description: "List all gateway and extension methods with schemas",
    inputSchema: z.object({}),
    source: "gateway",
  },
  {
    method: "gateway.list_extensions",
    description: "List loaded extensions and their methods",
    inputSchema: z.object({}),
    source: "gateway",
  },
  {
    method: "gateway.subscribe",
    description: "Subscribe to events",
    inputSchema: z.object({
      events: z.array(z.string()).optional(),
      exclusive: z.boolean().optional().describe("Last subscriber wins — only one client receives"),
    }),
    source: "gateway",
  },
  {
    method: "gateway.unsubscribe",
    description: "Unsubscribe from events",
    inputSchema: z.object({
      events: z.array(z.string()).optional(),
    }),
    source: "gateway",
  },
  {
    method: "gateway.restart_extension",
    description: "Restart an extension host process (manual HMR for non-hot extensions)",
    inputSchema: z.object({
      extension: z.string().describe("Extension ID to restart (e.g. session, codex, voice)"),
    }),
    source: "gateway",
  },
];

function requiredOptional(schema: z.ZodTypeAny): { required: string[]; optional: string[] } {
  const json = zodToJsonSchema(schema, "schema") as {
    definitions?: { schema?: { properties?: Record<string, unknown>; required?: string[] } };
  };
  const root = json.definitions?.schema;
  const props = Object.keys(root?.properties || {});
  const req = new Set(root?.required || []);
  return {
    required: props.filter((p) => req.has(p)),
    optional: props.filter((p) => !req.has(p)),
  };
}

function methodRows(methods: MethodDef[]): string {
  const sorted = [...methods].sort((a, b) => a.method.localeCompare(b.method));
  const rows = sorted.map((m) => {
    const io = requiredOptional(m.inputSchema);
    const required = io.required.length ? io.required.map((p) => `\`${p}\``).join(", ") : "none";
    const optional = io.optional.length ? io.optional.map((p) => `\`${p}\``).join(", ") : "none";
    return `| \`${m.method}\` | ${required} | ${optional} | ${m.description} |`;
  });
  return [
    "| Method | Required Params | Optional Params | Description |",
    "| --- | --- | --- | --- |",
    ...rows,
  ].join("\n");
}

function extensionMethods(): MethodDef[] {
  const exts = [
    createSessionExtension(),
    createVoiceExtension(),
    createIMessageExtension(),
    createChatExtension(),
    createControlExtension(),
    createMemoryExtension(),
    createHooksExtension(),
    createDominatrixExtension(),
    createCodexExtension(),
  ];

  const out: MethodDef[] = [];
  for (const ext of exts) {
    for (const method of ext.methods) {
      out.push({
        method: method.name,
        description: method.description,
        inputSchema: method.inputSchema,
        source: "extension",
      });
    }
  }
  return out;
}

const content = `# Claudia API Reference\n\nThis file is generated by \`scripts/generate-api-reference.ts\`.\n\n## Gateway API (port 30086, \`/ws\`)\n\n${methodRows(gatewayMethods)}\n\n## Extension API (via gateway)\n\n${methodRows(extensionMethods())}\n\n## Notes\n\n- Multi-word methods use snake_case (for example \`session.get_or_create_workspace\`, \`session.send_tool_result\`).\n- Source of truth is the code and schemas; regenerate after API changes.\n`;

writeFileSync(join(process.cwd(), "docs", "API-REFERENCE.md"), content);
console.log("[docs] Wrote docs/API-REFERENCE.md");
